myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/coupons/urls.py
from django.urls import path
from . import views

app_name = 'coupons'

urlpatterns = [
    path('apply/', views.coupon_apply, name='apply'),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('done/', views.payment_done, name='done'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('<str:ref>/', views.verify_payment, name="verify-payment"),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search_product', views.search_product, name='search-product'),
]

myshop/cart/models.py
from django.db import models

# Create your models here.

myshop/cart/forms.py
from django import forms
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=PRODUCT_QUANTITY_CHOICES, coerce=int, label="")
    override = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_id = ''
        self.helper.form_method = 'post'
        self.helper.form_tag = False
        self.helper.add_input(Submit('submit', 'submit'))

myshop/cart/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from shop.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from coupons.forms import CouponApplyForm
from shop.recommender import Recommender

@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        cart.add(product=product, quantity=cd['quantity'], override_quantity=cd['override'])
    return redirect('cart:cart_detail')

@require_POST
def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    if cart:
        return redirect('cart:cart_detail')
    return redirect('/')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(initial={'quantity': item['quantity'], 'override': True})
    coupon_apply_form = CouponApplyForm()

    r = Recommender()
    cart_products = [item['product'] for item in cart]
    recommended_products = r.suggest_products_for(cart_products, max_results=4)

    return render(request, 'cart/detail.html', {'cart': cart, 'coupon_apply_form': coupon_apply_form, 'recommended_products': recommended_products})

myshop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}

{% load crispy_forms_tags %}

{% load static %}
{% load i18n %}

{% block title %}
    Your shopping cart
{% endblock %}

{% block head %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://www.w3shools.com/w3css/4/w3.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="css/custom.css" >
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


<style>
input[type=submit] {
    width: 80px;
    padding:  5px;
    margin: 8px 0;
    display: ;
    border: none;
    border-radius:;
    box-sizing: border-box;
    }

form{
    display:inline;

}
spa {
    display: inline-block;
    background-color: #d1d5db;
    width: 70px;
    height: 140px;
    }

.bat {
    width: 520px;
}
.block {
    width: 30px;
    border: non;
    height: 45px;
    display: inline-block;
    }
.bt {
    border: none;
    padding: 20px;
}

.grid-container{
    display: grid;
    column-gap:50px;
    background-color: #2196F3;
    padding: 10px;
    }

.grid-item{
    text-align: center;
    }


</style>


{% endblock %}


{% block content %}
<body>
<div class="container">
<h1>Your shopping cart</h1>

    <!-- Cart Start -->
<div class="cart-page">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-8">
                <div class="cart-page-inner">
                    <div class="table-responsive text-nowrap">
                        <table class="table table-bordered">
                            <thead class="text-muted">
                            <tr>
                                <th>Image</th>
                                <th>Product</th>
                                <th>Quantity</th>
                                <th>Unit price</th>
                                <th>Total</th>
                                <th>Remove</th>
                            </tr>
                            </thead>
                            <tbody class="align-middle">
                            {% for item in cart %}
                            {% with product=item.product %}

                            <tr>
                                <td class="text-center">
                                    <div class="img">
                                        <a href="{{ product.get_absolute_url }}"><img  height="40" width="40" alt="Image" src="{% if product.image %}{{ product.image.url }} {% else %}{% static "img/no_image.png" %}{% endif %}"></a>
                                    </div>
                                </td>
                                <td class="text-center">{{ product.name }}</td>
                                <td>
                                    <div class="qty text-center">
                                        <form class="" action="{% url "cart:cart_add" product.id %}" method="post">
                                                {{ item.update_quantity_form.quantity|as_crispy_field }}
                                        {{ item.update_quantity_form.override }}
                                        <button class="fa fa-refresh text-success btn btn-white" type="submit" value="Update" >
                                            {% csrf_token %}</button>
                                        </form>
                                    </div>
                                </td>
                                <td class="text-center">&#8358;{{ item.price }}</td>
                                <td class="text-center">&#8358;{{ item.total_price }}
                                </td>
                                <td class="text-center">
                                    <form class="form-inline" action="{% url "cart:cart_remove" product.id %}" method="post">
                                    <button class="bi bi-trash text-success btn btn-white" type="submit" value="Remove">
                                        {% csrf_token %}</button>
                                    </form>
                                </td>
                            </tr>

                            {% endwith %}
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="cart-page-inner ">
                    <div class="row">
                        <div class="col-md-12">
                            <div class="container border bg-light">
                            <div class="coupon"><br>
                                <p>Apply Coupon to get discount:</p>
                                <form action="{% url "coupons:apply" %}" method="post">
                                {{ coupon_apply_form|crispy }}
                                <input class="btn btn-success rounded-pill" type="submit" value="Apply">
                                {% csrf_token %}
                                </form>
                            </div></div><br>
                        </div>
                        <div class="col-md-12"><br>
                            <div class="container border bg-light">
                                <div class="cart-summary">
                                    <div class="cart-content"><br>
                                        <h1 class="text-center">Cart Summary</h1>
                                        <div class="card-price-list d-flex justify-content-between align-items-center">
                                            <div class="item">
                                                <p class="text-muted">Sub Total</p>
                                            </div>
                                            <div class="price">
                                                <p>&#8358;{{ cart.get_total_price }}</p>
                                            </div>
                                        </div>
                                        {% if cart.coupon %}
                                        <div class="card-price-list d-flex justify-content-between align-items-center">
                                            <div class="item">
                                                <p class="text-muted">Discount</p>
                                            </div>
                                            <div class="price">
                                                <p>- &#8358;{{ cart.get_discount|floatformat:2 }}({{ cart.coupon.discount }}% off)</p>
                                            </div>
                                        </div>
                                        {% endif %}
                                        <div class="card-price-list d-flex justify-content-between align-items-center">
                                            <div class="item">
                                                <p class="text-muted">Shipping Cost</p>
                                            </div>
                                            <div class="price">
                                                <p>&#8358;{{cart.get_shipping_cost}}.00</p>
                                            </div>
                                        </div>
                                        <div class="card-price-list d-flex justify-content-between align-items-center">
                                            <div class="item">
                                                <p class="text-muted">Service fee</p>
                                            </div>
                                            <div class="price">
                                                <p>&#8358;{{cart.service_fee}}</p>
                                            </div>
                                        </div>
                                        <div class="card-price-subtotal d-flex justify-content-between align-items-center">
                                            <div class="total-text">
                                                <p class="text-muted">Total Price</p>
                                            </div>
                                            <div class="total-price">
                                                <p>&#8358;{{ cart.get_total_price_after_discount|floatformat:2 }}</p>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="cart-btn d-flex justify-content-between align-items-center">
                                        <div class="item">
                                            <p>
                                                <a class="btn btn-outline-success rounded-pill" role="button" href="{% url "shop:product_list" %}" ><i class="text-success fa fa-chevron-left"></i>   Continue shopping</a>
                                            </p>
                                        </div>
                                        <div class="price">
                                            <p>
                                                <a class="btn btn-success rounded-pill" role="button" href="{% url "orders:order_create" %}" >Checkout Now  <i class="text-light fa fa-chevron-right"></i></a>
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <br>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- Cart End -->
</div>
</body>

{% endblock %}