myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.order_create, name='order_create'),
    path('done/', views.payment_done, name='done'),
    path('canceled/', views.payment_canceled, name='canceled'),
    path('<str:ref>/', views.verify_payment, name="verify-payment"),
    path('admin/order/<int:order_id>/', views.admin_order_detail, name='admin_order_detail'),
    path('admin/order/<int:order_id>/pdf/', views.admin_order_pdf, name='admin_order_pdf'),
]

myshop/orders/models.py
from django.db import models
from shop.models import Product
import secrets
from .paystack import PayStack
from decimal import Decimal
from django.core.validators import MinValueValidator, MaxValueValidator
from coupons.models import Coupon
from django.urls import reverse
from django.contrib.auth.models import User
from cart.cart import Cart

class Order(models.Model):
    STATUS = [
        ('Dala', ('Dala')),
        ('Fagge', ('Fagge')),
        ('Kano municipal', ('Kano municipal')),
        ('Kumbotso', ('Kumbotso')),
        ('Nassarawa', ('Nassarawa')),
        ('Rimi', ('Rimi')),
        ('Tarauni', ('Tarauni')),
        ('Ungogo', ('Ungogo')),
    ]
    user = models.ForeignKey(User, null=True, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    email = models.EmailField()
    address = models.CharField(max_length=250)
    phone_number = models.CharField(max_length=20)
    postal_code = models.CharField(max_length=20)
    city = models.CharField(max_length=100, choices=STATUS, default='NASSARAWA')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    verified = models.BooleanField(default=False)
    ref = models.CharField(max_length=200)
    coupon = models.ForeignKey(Coupon, related_name='orders', null=True, blank=True, on_delete=models.SET_NULL)
    discount = models.IntegerField(default=0, validators=[MinValueValidator(0), MaxValueValidator(100)])


    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return f'Order {self.id}'

    def save(self, *args, **kwargs) -> None:
        while not self.ref:
            ref = secrets.token_urlsafe(10)
            object_with_similar_ref = Order.objects.filter(ref=ref)
            if not object_with_similar_ref:
                self.ref = ref
        super().save(*args, **kwargs)


    def get_total_cost(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        return total_cost - total_cost * (self.discount / Decimal(100)) + self.shipping() + self.service_fee()

    def service_fee(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        a = (total_cost)*(Decimal(5)/Decimal(100))
        c = round(a, 2)
        return c

    def shipping(self):
        total_cost = sum(item.get_cost() for item in self.items.all())
        if total_cost >= 30000:
            shipping_cost = 0
        elif total_cost in range(25000, 30000):
            shipping_cost = 2000
        elif total_cost in range(20000, 2500):
            shipping_cost = 1500
        elif total_cost in range(10000, 20000):
            shipping_cost = 1000
        elif total_cost in range(5000, 10000):
            shipping_cost = 750
        elif total_cost in range(1, 5000):
            shipping_cost = 500
        else:
            shipping_cost = 0
        return shipping_cost

    def amount_value(self) -> int:
        return self.get_total_cost()*100

    def verify_payment(self):
        paystack = PayStack()
        status, result = paystack.verify_payment(self.ref, self.get_total_cost())
        if status:
            if result['amount'] / 100 == self.get_total_cost():
                self.verified = True
            self.save()
        if self.verified:
            return True
        return False

    def get_absolute_url(self):
        return reverse('account:order_details', args=[self.id])

class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    def get_cost(self):
        return self.price * self.quantity

    def get_absolute_url(self):
        return self.product.get_absolute_url()

myshop/orders/forms.py
from django import forms
from .models import Order
from django.forms import TextInput

class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'email', 'address', 'phone_number', 'postal_code', 'city']
        widgets = {
            "first_name": TextInput(
                attrs={
                    "placeholder": "Enter your first name"
                }
            ),
            "last_name": TextInput(
                attrs={
                    "placeholder": "Enter your last name"
                }
            ),
            "email": TextInput(
                attrs={
                    "placeholder": "e.g. jason@example.com"
                }
            ),
            "address": TextInput(
                attrs={
                    "placeholder": "Enter your delivery address"
                }
            ),
            "postal_code": TextInput(
                attrs={
                    "placeholder": "e.g. 70098"
                }
            ),
            "phone_number": TextInput(
                attrs={
                    "placeholder": "e.g. 08012121212"
                }
            )
        }

myshop/orders/views.py
from django.http.request import HttpRequest
from django.http.response import HttpResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse
from .tasks import order_created
from django.shortcuts import render, redirect
from .models import OrderItem
from .forms import OrderCreateForm
from cart.cart import Cart
from django.conf import settings
from .models import Order
from django.contrib import messages
from .taskss import payment_completed
from django.contrib.auth.decorators import login_required

@login_required
def order_create(request: HttpRequest) -> HttpResponse:
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save(commit=False)
            if request.user.is_authenticated:
                order.user = request.user
            if cart.coupon:
                order.coupon = cart.coupon
                order.discount = cart.coupon.discount
            order.save()
            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'], quantity=item['quantity'])
            # clear the cart
            cart.clear()
            # launch asynchronous task
            order_created.delay(order.id)
            # set the order in the session
            request.session['order_id'] = order.id
            # redirect for payment
            return render(request, 'orders/order/process.html', {'order': order, 'paystack_public_key': settings.PAYSTACK_PUBLIC_KEY})
    else:
        form = OrderCreateForm()
    return render(request, 'orders/order/create.html', {'cart': cart, 'form': form})


def payment_done(request):
    return render(request, 'orders/order/done.html')

def payment_canceled(request):
    return render(request, 'orders/order/canceled.html')


def verify_payment(request: HttpResponse, ref: str) -> HttpResponse:
    payment = get_object_or_404(Order, ref=ref)
    verified = payment.verify_payment()
    order_id = request.session.get('order_id')
    order = get_object_or_404(Order, id=order_id)
    if verified:
        # launch asynchronous task
        payment_completed.delay(order.id)
        messages.success(request, "verification successful")
    else:
        messages.error(request, "verification failed")
        return redirect('orders:canceled')
    return redirect('orders:done')

from django.contrib.admin.views.decorators import staff_member_required
from django.shortcuts import get_object_or_404
from .models import Order

@staff_member_required
def admin_order_detail(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'admin/orders/order/detail.html', {'order': order})

from django.conf import settings
from django.http import HttpResponse
from django.template.loader import render_to_string
import weasyprint

@staff_member_required
def admin_order_pdf(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    html = render_to_string('orders/order/pdf.html', {'order': order})
    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=order_{order.id}.pdf'
    weasyprint.HTML(string=html).write_pdf(response, stylesheets=[weasyprint.CSS(settings.STATIC_ROOT + 'css/pdf.css')])
    return response

myshop/orders/templates/orders/order/canceled.html
{% extends "shop/base.html" %}

{% block title %}Payment canceled{% endblock %}

{% block content %}
    <h1>Your payment has not been processed</h1>
    <p>There was a problem processing your payment.</p>
{% endblock %}

myshop/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}


{% load crispy_forms_tags %}

{% load static %}
{% load i18n %}


{% block title %}
{{ product.name }}
{% endblock %}
{% block head %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://www.w3shools.com/w3css/4/w3.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="css/custom.css" >
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


<style>
bod{

    background: #d1d5db;
}


.form{

    position: static;
}

.form .fa-search{

    position: relative;
    top:57px;
    left: 20px;
    color: #9ca3af;

}

.form-input{

    height: 55px;
    text-indent: 33px;
    border-radius: 10px;
    background: #d1d5db;
}

.form-input:focus{

    box-shadow: none;
    border:none;
    background: #d1d5db;
}
</style>

<style>
    /*
    DEMO STYLE
*/

@import "https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700";
 {
    font-family: 'Poppins', sans-serif;
    background: #fafafa;
}

p {
    font-family: 'Poppins', sans-serif;
    font-size: 1.1em;
    font-weight: 300;
    line-height: 1.7em;
    color: #999;
}

a,
a:hover,
a:focus {
    color: inherit;
    text-decoration: none;
    transition: all 0.3s;
}

.navbar {
    padding: 15px 10px;
    background: #fff;
    border: none;
    border-radius: 0;
    margin-bottom: 40px;
    box-shadow: 1px 1px 3px rgba(0, 0, 0, 0.1);
}

.navbar-btn {
    box-shadow: none;
    outline: none !important;
    border: none;
}

.line {
    width: 100%;
    height: 1px;
    border-bottom: 1px dashed #ddd;
    margin: 40px 0;
}

/* ---------------------------------------------------
    SIDEBAR STYLE
----------------------------------------------------- */

.wrapper {
    display: flex;
    width: 100%;
    align-items: stretch;
}

#sidebar {
    min-width: 250px;
    max-width: 250px;
    background: ;
    color: #fff;
    transition: all 0.3s;
}

#sidebar.active {
    margin-left: -250px;
}

#sidebar .sidebar-header {
    padding: 20px;
    background: ;
    color: #080808;

}

#sidebar ul.components {
    padding: 20px 0;
    border-bottom: 1px solid #47748b;
}

#sidebar ul p {
    color: #fff;
    padding: 10px;
}

#sidebar ul li a {
    padding: 10px;
    font-size: 1.1em;
    display: block;
}

#sidebar ul li a:hover {
    color: #7386D5;
    background: #fff;
}

#sidebar ul li.active>a,
a[aria-expanded="true"] {
    color: #fff;
    background: #6d7fcc;
}

a[data-toggle="collapse"] {
    position: relative;
}

.dropdown-toggle::after {
    display: block;
    position: absolute;
    top: 50%;
    right: 20px;
    transform: translateY(-50%);
}

ul ul a {
    font-size: 0.9em !important;
    padding-left: 30px !important;
    background: ;
    color: #080808;

}

ul.CTAs {
    padding: 20px;
}

ul.CTAs a {
    text-align: center;
    font-size: 0.9em !important;
    display: block;
    border-radius: 5px;
    margin-bottom: 5px;
}

a.download {
    background: #fff;
    color: #7386D5;
}

a.article,
a.article:hover {
    background: #6d7fcc !important;
    color: #fff !important;
}

/* ---------------------------------------------------
    CONTENT STYLE
----------------------------------------------------- */

#content {
    width: 100%;
    padding: 20px;
    min-height: 100vh;
    transition: all 0.3s;
}

/* ---------------------------------------------------
    MEDIAQUERIES
----------------------------------------------------- */

@media (max-width: 768px) {
    #sidebar {
        margin-left: -250px;
    }
    #sidebar.active {
        margin-left: 0;
    }
    #sidebarCollapse span {
        display: none;
    }
}

.grid-container {
    display: grid;
    row-gap: 50px;
    column-gap: 50px;
    grid-template-columns: auto auto auto auto;
    background-color: ;
    padding: 10px;

}
.btn-round {
    border-radius: 50px;
    }

.grid-item {
    background-color: rgba(255, 255, 255, 0.8);
    border: 1px solid rgba(0, 0, 0, 0.8);
    padding: 10px;
    font-size: 15px;
    text-align: center;
    height: 100%;
}


body{
    background:;
}
.details {
            border: 1.5px solid grey;
            color: #212121;
            width: 100%;
            height: auto;
            box-shadow: 0px 0px 10px #212121;
        }

         .cartt{
            background-color: #212121;
            color: white;
            margin-top: 10px;
            font-size: 12px;
            font-weight: 900;
            width: 100%;
            height: 39px;
            padding-top: 9px;
            box-shadow: 0px 5px 10px  #212121;
        }

        .card {
            width: fit-content;
        }

        .card-body {
            width: fit-content;
        }

        .btn {
            border-radius: 0;
        }


        .card {
            box-shadow: 0 20px 40px rgba(0, 0, 0, .2);
            border-radius: 5px;
            padding-bottom: 10px;
        }



</style>


{% endblock %}


{% block content %}


<div class="container">
    <h1>Checkout</h1>

    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <br>
                <div class="order-info border bg-light">
                <div class="container">
                    <br>
                    <h3>  Your order</h3>
                    <ul>
                        {% for item in cart %}
                            <li class="text-success">
                                {{ item.quantity }}x {{ item.product.name }}
                                <span> &#8358;{{ item.total_price|floatformat:2 }}</span>
                            </li>
                        {% endfor %}
                        {% if cart.coupon %}
                        <li>
                            "{{ cart.coupon.code }}" ({{ cart.coupon.discount }}% off)
                            <span class="neg"> - &#8358;{{ cart.get_discount|floatformat:2 }}</span>
                        </li>
                        {% endif %}
                    </ul>
                    <p class="text-dark"> Shipping Cost: &#8358;{{cart.get_shipping_cost}}.00</p>
                    <p class="text-dark"> Service Fee: &#8358;{{cart.service_fee}}</p>
                    <p class="text-dark"> Total: &#8358;{{ cart.get_total_price_after_discount|floatformat:2 }}</p>
                </div>
            </div>
        </div>

        <div class="col-lg-6">
            <br>
            <div class="container border bg-light">
                <br>
                <h2>Billing Details</h2>
                <form method="post" class="order-form">
                    <div class="form-row">
                        <div class="form-group col-md-6 mb-0">
                            {{ form.first_name|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.last_name|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6 mb-0">
                            {{ form.email|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.phone_number|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-12 mb-0">
                            {{ form.address|as_crispy_field }}
                        </div>
                    </div>
                    <div class="form-row">
                        <div class="form-group col-md-6 mb-0">
                            {{ form.postal_code|as_crispy_field }}
                        </div>
                        <div class="form-group col-md-6 mb-0">
                            {{ form.city|as_crispy_field }}
                        </div>
                    </div>
                    <p><button class="btn btn-success rounded-pill type="submit"> Place order (&#8358;{{ cart.get_total_price_after_discount|floatformat:2 }})</button></p>
                    {% csrf_token %}
                </form>
            </div>
        </div>
            <br>
    </div>
</div>
<br>
</div>
        {% endblock %}

myshop/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}
    Thank you
{% endblock %}

{% block content %}
    <h1>Thank you</h1>

    <p>Your order has been successfully completed. Your order number is <strong>{{ order.id }}</strong>.</p>
{% endblock %}

myshop/orders/templates/orders/order/pdf.html
<html>
<body>
<h1>My Shop</h1>
<p>
    Invoice no. {{ order.id }}</br>
    Ref. {{ order.ref }}</br>
    <span class="secondary">
        {{ order.created|date:"M d, Y" }}
    </span>
</p>

<h3>Bill to</h3>

<p>
    {{ order.first_name }} {{ order.last_name }}<br>
    {{ order.email }}<br>
    {{ order.address }}<br>
    {{ order.phone_number }}<br>
    {{ order.postal_code }}, {{ order.city }}
</p>

<h3>Items bought</h3>
<table>
    <thead>
    <tr>
        <th>Product</th>
        <th>Price</th>
        <th>Quantity</th>
        <th>Cost</th>
    </tr>
    </thead>
    <tbody>
    {% for item in order.items.all %}
    <tr class="row{% cycle "1" "2" %}">
        <td class="text-center">{{ item.product.name }}</td>
        <td class="text-center">&#8358;{{ item.price }}</td>
        <td class="text-center">{{ item.quantity }}</td>
        <td class="text-center">&#8358;{{ item.get_cost }}</td>
    </tr>
    {% endfor %}
    <tr class="shipping">
        <td colspan="3">Shipping cost</td>
        <td class="text-center">&#8358;{{ order.shipping }}.00</td>
    </tr>
    <tr class="shipping">
        <td colspan="3">Service fee</td>
        <td class="text-center">&#8358;{{ order.service_fee }}.00</td>
    </tr>
    {% if order.coupon %}
    <tr class="discount">
            <td colspan="3">Discount</td>
        <td class="text-center"> <span class="neg">- &#8358;{{ order.discount }}</span>({{ order.coupon.discount }}% off)</td>

        </tr>
    {% endif %}

    <tr class="total">
        <td colspan="3">Total</td>
        <td class="text-center">&#8358;{{ order.get_total_cost }}</td>
    </tr>
    </tbody>
</table>
<span class="{% if order.verified %}verified{% else %}pending{% endif %}">
    {% if order.verified %}Paid{% else %}Pending payment{% endif %}
</span>
</body>
</html>

myshop/orders/templates/orders/order/process.html
{% extends "shop/base.html" %}

{% load crispy_forms_tags %}

{% load static %}
{% load i18n %}

{% block title %}
Your shopping cart
{% endblock %}

{% block head %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://www.w3shools.com/w3css/4/w3.css">
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<link rel="stylesheet" href="css/custom.css" >
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


<style>
input[type=submit] {
    width: 80px;
    padding:  5px;
    margin: 8px 0;
    display: ;
    border: none;
    border-radius:;
    box-sizing: border-box;
    }

form{
    display:inline;

}
spa {
    display: inline-block;
    background-color: #d1d5db;
    width: 70px;
    height: 140px;
    }

.bat {
    width: 520px;
}
.block {
    width: 30px;
    border: non;
    height: 45px;
    display: inline-block;
    }
.bt {
    border: none;
    padding: 20px;
}

.grid-container{
    display: grid;
    column-gap:50px;
    background-color: #2196F3;
    padding: 10px;
    }

.grid-item{
    text-align: center;
    }


</style>


{% endblock %}


{% block content %}
<div class="container">
    <div class="d-flex row justify-content-center align-items-center py-md-5 py-3" style="min-height: 90vh;">
        <div class="col-12 text-center">
            <h5 class="text-dark">Make payment for:<span class="text-dark"> &#8358;{{ order.get_total_cost }}</span></h5>
            <hr>
                <script src="https://js.paystack.co/v1/inline.js"></script>
                <button class="btn btn-large btn-success rounded-pill" onclick="payWithPayStack()" id="django-paystack-button">Make Payment</button>
        </div>
    </div>
</div>
<script>
    function payWithPayStack(){
        let currency = "NGN";
        let plan = "";
        let ref = "{{ order.ref }}"
        let obj = {
            key: "{{ paystack_public_key }}",
            email: "{{ order.email }}",
            amount: "{{ order.amount_value }}",
            ref : ref,
            callback: function(response){
                window.location.href = "{% url 'orders:verify-payment' order.ref %}";
            }
        }

        if (Boolean(currency)){
            obj.currency = currency.toUpperCase()
        }
        if (Boolean(plan)){
            obj.plan = plan;
        }
        var handler = PaystackPop.setup(obj);
        handler.openIframe();
    }
</script>
{% endblock %}