myshop/account/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.urls import reverse_lazy

app_name = 'account'

urlpatterns = [
    # post views
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('edit/', views.edit, name='edit'),
    path('register/', views.register, name='register'),
    path('register_done/', views.register, name='register_done'),
    path('my_account/', views.my_account, name='my_account'),
    path('order_details/', views.order_details, name='order_details'),
    # change password urls
    path('password_change/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('account:password_change_done')), name='password_change'),
    path('password_change/done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
    # reset password urls
    path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
]

myshop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

myshop/myshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('coupons/', include('coupons.urls', namespace='coupons')),
    path('', include('shop.urls', namespace='shop')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path
from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
    path('search_product', views.search_product, name='search-product'),
]

myshop/shop/models.py
from django.urls import reverse
from django.db import models

class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, unique=True)
    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category', args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category, related_name='products', on_delete=models.CASCADE)
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='products/%Y/%m/%d', blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:product_detail', args=[self.id, self.slug])

myshop/shop/views.py
from cart.forms import CartAddProductForm
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    object_list = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        object_list = object_list.filter(category=category)
    paginator = Paginator(object_list, 4)
    page = request.GET.get('page')
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        products = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/product/list.html', {'category': category, 'categories': categories, 'page': page, 'products': products})


from .recommender import Recommender

def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    cart_product_form = CartAddProductForm()

    r = Recommender()
    recommended_products = r.suggest_products_for([product], 4)

    return render(request, 'shop/product/detail.html', {'product': product, 'cart_product_form': cart_product_form, 'recommended_products': recommended_products})

def search_product(request):
    if request.method == "POST":
        query_name = request.POST.get('name', None)
        if query_name:
            results = Product.objects.filter(name__contains=query_name)
            return render(request, 'shop/product/search_product.html', {"results":results, 'query_name': query_name,})

    return render(request, 'shop/product/search_product.html')

myshop/shop/templates/shop/base.html
<!DOCTYPE html>
<!-- code by webdevtrick ( https://webdevtrick.com ) -->
<html>
{% load static %}
<head>
    {% block head %}
    {% load static %}
    <title>UKturajo</title>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="css/custom.css" >
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
{% endblock %}
    <style>
    /** code by webdevtrick ( https://webdevtrick.com ) **/
body {
	margin: 0;
	padding: 0;
}
* {
	font-family: Arial, Helvetica, sansa-serif;
}
.nav-bar1 {
  height: 70px;
  background: #FFFFFF;
  border: 1px solid #d8d8d8;
}

.brand {
  position: absolute;
  padding-left: 20px;
  float: left;
  line-height: 60px;
  text-transform: uppercase;
  font-size: 2.0em;
}
.brand a img {
	max-height: 70px;
}
.brand a,
.brand a:visited {
  color: #ffffff;
  text-decoration: none;
}

.nav-container {
  max-width: 1000px;
  margin: 0 auto;
}

nav2 {
  float: right;
}
nav2 ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
nav2 ul li {
  float: left;
  position: relative;
}
nav2 ul li a,
nav2 ul li a:visited {
  display: block;
  padding: 0 20px;
  line-height: 68px;
  background: #FfFfFF;
  color: black;
  text-decoration: none;
}
nav2 ul li a:hover,
nav2 ul li a:visited:hover {
  background: #2ab1ce;
  color: #ffffff;
}
nav2 ul li a:not(:only-child):after,
nav2 ul li a:visited:not(:only-child):after {
  padding-left: 4px;
  content: ' ▾';
}
nav2 ul li ul li {
  min-width: 190px;
}
nav2 ul li ul li a {
  padding: 15px;
  line-height: 20px;
}

.nav-dropdown {
  position: absolute;
  display: none;
  z-index: 1;
  box-shadow: 0 3px 12px rgba(0, 0, 0, 0.15);
}
.nav-mobile {
  display: none;
  position: absolute;
  top: 0;
  right: 0;
  background: #FfFfFF;
  height: 67px;
  width: 70px;
}

@media only screen and (max-width: 798px) {
  .nav-mobile {
    display: block;
  }

  nav2 {
    width: 100%;
    padding: 70px 0 15px;
  }

  nav2 ul {
    display: none;
  }

  nav2 ul li {
    float: none;
  }

  nav2 ul li a {
    padding: 5px;
    line-height: 17px;
	padding-left: 25%;
  }

  nav2 ul li ul li a {
    padding-left: 30%;
  }

  .nav-dropdown {
    position: static;
  }
	.brand a img {
		max-height: 60px;
		margin-top: 5px;
	}
}
@media screen and (min-width: 799px) {
  .nav-list {
    display: block !important;
  }
}
#nav-toggle {
  position: absolute;
  left: 18px;
  top: 28px;
  cursor:
  pointer;
  padding: 10px 35px 16px 0px;
}
#nav-toggle span,
#nav-toggle span:before,
#nav-toggle span:after {
  cursor: pointer;
  border-radius: 1px;
  height: 5px;
  width: 35px;
  background: black;
  position: absolute;
  display: block;
  content: '';
  transition: all 300ms ease-in-out;
}
#nav-toggle span:before {
  top: -10px;
}
#nav-toggle span:after {
  bottom: -10px;
}
#nav-toggle.active span {
  background-color: transparent;
}
#nav-toggle.active span:before, #nav-toggle.active span:after {
  top: 0;
}
#nav-toggle.active span:before {
  transform: rotate(45deg);
}
#nav-toggle.active span:after {
  transform: rotate(-45deg);
}


article {
  max-width: 1000px;
  margin: 0 auto;
  padding: 10px;
}

.container1 {
    background-image: url("{% static 'mysite/images/til.jpg' %}");
    background-size: cover;
    margin: auto;
    padding: 10;
    top: 50;
    background-position: center center;
    text-align: enter;
    text-color: white;
    background-repeat: no repeat;
    height: 50px;
    opacity: 0.9;
    overflow: hidden;
    background: blac;
}
.about p {
    font-size: 130%;
}
.view {
  height: 100%;
}

@media (max-width: 740px) {
  html,
  body,
  header,
  .view {
    height: 100vh;
  }
}

.top-nav-collapse {
  background-color: #78909c !important;
}

.navbar1:not(.top-nav-collapse) {
  background: transparent !important;
}

@media (max-width: 991px) {
  .navbar1:not(.top-nav-collapse) {
    background: #78909c !important;
  }
}



h5 {
  letter-spacing: 3px;
  color:white;
  font-size:200%;
}

body {
  margin: 0;
  background-color: #;
  font-family: Arial, Helvetica, sans-serif;
  }
  h2 {
  font-size: 1em;
  text-transform: capitalize;
}

/* 1. Fallback background-image, if linear-gradient isn't supported. */
.container3 {
  padding: 2em;
  background-image: url('{% static 'mysite/images/til.jpg' %}');
  /* 1 */
  background-image:
    linear-gradient(hsla(300, 80%, 20%, 0.7),90%,coral),
    url('{% static 'mysite/images/til.jpg' %}');
  background-position: center center;
  background-size: cover;
    height:600px;
    background-repeat: no-repeat;
}

.content {
  text-align: center;
  color: white;
}
.hr-light {
  border-top: 3px solid #fff;
  width: 80px;
}
.footer {
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: #14A44D;
   color: black;
   text-align: center;
}

ul1 {
    padding: 2px;
    font-size: 35px;
    width: 30px;
    margin: 5px 2px;
    border-radius: 50%;
    list-style: none;
    transition: 6%
    line-height: 60%;
    color: #000;
}

li1 {
    list-style: none;
    margin: 0 10px;
}

.fa {
    color: #000;
    transition: 6%;
    line-height: 60px;
}

h2 {
font-size: 150%;
color: #000;
}

h1 {
font-size: 200%;
color: #000;
.container2 ul li a  {
    position: relative;
    display: block;
    width: 60px;
    padding: 10;
    height: 60px;
    border-radius: 90%;
    background-color:#fff;
    text-align: center;
    transition: 6%;
    box-shadow: 0 5px 4px rgba(0,0,0,.5);
}

 li1:hover{
    transform: translate(0,-10px);










</style>
    <style>
        p {
            font-size: 120%;
    </style>
</head>
<body>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
    <script  src="function.js"></script>
    <script>/** code by webdevtrick ( https://webdevtrick.com ) **/
$(document).on('ready', function() {

  $('.field').on('focus', function() {
    $('body').addClass('is-focus');
  });

  $('.field').on('blur', function() {
    $('body').removeClass('is-focus is-type');
  });

  $('.field').on('keydown', function(event) {
    $('body').addClass('is-type');
    if((event.which === 8) && $(this).val() === '') {
      $('body').removeClass('is-type');
    }
  });

});

</script>


<section class="nav-bar1">
        <div class="nav-container">
            <div class="brand mt-2">
                <a class="text-success" href="/" class="logo text-dark">Allshops</a>
            </div>
            </div>
            <nav2>
                <div class="nav-mobile"><a id="nav-toggle" href="#!"><span></span></a></div>
                <ul class="nav-list">
                    <li>
                        <a class="text-success" href="/">Home</a>
                    </li>
                    {% if request.user.is_authenticated %}

                    <li>

                        <a class="text-success" href="{% url "account:password_change" %}">Change password</a>

                    </li>
                    {% else %}
                    {% endif %}
                    <li>
                        {% if request.user.is_authenticated %}

                        <a class="text-success" href="{% url "account:logout" %}">Logout</a>
                        {% else %}
                        <a class="text-success" href="{% url "account:login" %}">Log-in</a>
                        {% endif %}
                    </li>
                </ul>
            </nav2>
        </div>
    </section>
</div>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script  src="function.js"></script>
<script>/** code by webdevtrick ( https://webdevtrick.com ) **/
(function($) {
  $(function() {
    $('nav2 ul li a:not(:only-child)').click(function(e) {
      $(this).siblings('.nav-dropdown').toggle();
      $('.dropdown').not($(this).siblings()).hide();
      e.stopPropagation();
    });
    $('html').click(function() {
      $('.nav-dropdown').hide();
    });
    $('#nav-toggle').click(function() {
      $('nav2 ul').slideToggle();
    });
    $('#nav-toggle').on('click', function() {
      this.classList.toggle('active');
    });
  });
})(jQuery);
// Animations init
new WOW().init();

</script>


    <br>
    <div class="container">
        <div class="container1">
            <div class="d-flex bd-highlight">
                <div class="p-2 flex-grow-1 bd-highlight text-muted">
                    {% if request.user.is_authenticated %}
                        Hello {{ request.user.first_name }}!
                    {% else %}
                    {% endif %}
                </div>


                <div class="p-2 bd-highlight">
                    <span class="user">
                        <div>
                            <a href="{% url "cart:cart_detail" %}"></a>
                            <span class="cart text-dark">
                                {% with total_items=cart|length %}
                                    {% if total_items > 0 %}
                                        <a class="btn btn-success rounded-pill" href="{% url "cart:cart_detail" %}">
                                            <i class="bi bi-cart3"></i>
                                            <span class="badge">
                                                {{ total_items }}item(s) (&#8358;{{ cart.get_total_price_after_discount|floatformat:2 }})
                                            </span>
                                        </a>
                                    {% else %}
                                        <a class="btn btn-success text-light rounded-pill" >
                                            <i class="bi bi-cart3"></i>(0)
                                            {% endif %}
                                            {% endwith %}
                                        </a>
                            </span>
                        </div>
                    </span>
                </div>


                <div class="p-2 bd-highlight">
                    {% if request.user.is_authenticated %}
                        {% if section == "my_account" %}class="selected"{% endif %}
                            <a class="btn btn-success rounded-pill" href="{% url "account:my_account" %}">
                                <i class="bi bi-person"></i>
                            </a>

                        {% endif %}
                </div>
            </div>
        </div>
    </div>
        {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li class="{{ message.tags }} text-success">
                {{ message|safe }}
            </li>
            {% endfor %}
        </ul>
        {% endif %}
            {% block content %}
            {% endblock %}

</body>
        <br>
        <br>
        <div class="footer">
            <br>
            <div class="container2 mt-5 text-center">
                <h1>Get in touch</h1>
                <p class="text-light">ukturajo@gmail.com</p>
                <ul1>
                    <li1><a href="https://linkedin.com/in/usman-turajo-07511419a"><i class="fa fa-linkedin"></i></a></li1>
                    <li1><a href="https://github.com/uthman399"><i class="fa fa-github"></i></a></li1>
                    <li1><a href="https://linkedin.com/in/usman-turajo-07511419a"><i class="fa fa-twitter"></i></a></li1>
                    <li1><a href="https://github.com/uthman399"><i class="fa fa-instagram"></i></a></li1>
                </ul1>
            </div>
            <p class="text-light">Copyright @ 2022</p>
            <br>
        </div>


</html>

myshop/shop/templates/shop/navigation.html
<style>
body {
	margin: 0;
	padding: 0;
}
* {
	font-family: Arial, Helvetica, sansa-serif;
}
.nav-bar {
  height: 70px;
  background: #FFFFFF;
  border: 1px solid #d8d8d8;
}

.brand {
  position: absolute;
  padding-left: 20px;
  float: left;
  line-height: 60px;
  text-transform: uppercase;
  font-size: 2.0em;
}
.brand a img {
	max-height: 70px;
}
.brand a,
.brand a:visited {
  color: #ffffff;
  text-decoration: none;
}

.nav-container {
  max-width: 1000px;
  margin: 0 auto;
}

nav {
  float: right;
}
nav ul {
  list-style: none;
  margin: 0;
  padding: 0;
}
nav ul li {
  float: left;
  position: relative;
}
nav ul li a,
nav ul li a:visited {
  display: block;
  padding: 0 20px;
  line-height: 68px;
  background: #FfFfFF;
  color: black;
  text-decoration: none;
}
nav ul li a:hover,
nav ul li a:visited:hover {
  background: #2ab1ce;
  color: #ffffff;
}
nav ul li a:not(:only-child):after,
nav ul li a:visited:not(:only-child):after {
  padding-left: 4px;
  content: ' ▾';
}
nav ul li ul li {
  min-width: 190px;
}
nav ul li ul li a {
  padding: 15px;
  line-height: 20px;
}

.nav-dropdown {
  position: absolute;
  display: none;
  z-index: 1;
  box-shadow: 0 3px 12px rgba(0, 0, 0, 0.15);
}
.nav-mobile {
  display: none;
  position: absolute;
  top: 0;
  right: 0;
  background: #FfFfFF;
  height: 67px;
  width: 70px;
}

@media only screen and (max-width: 798px) {
  .nav-mobile {
    display: block;
  }

  nav {
    width: 100%;
    padding: 70px 0 15px;
  }
  nav ul {
    display: none;
  }
  nav ul li {
    float: none;
  }
  nav ul li a {
    padding: 15px;
    line-height: 20px;
	padding-left: 25%;

  }
  nav ul li ul li a {
    padding-left: 30%;
  }

  .nav-dropdown {
    position: static;
  }
	.brand a img {
		max-height: 60px;
		margin-top: 5px;
	}
}
@media screen and (min-width: 799px) {
  .nav-list {
    display: block !important;
  }
}
#nav-toggle {
  position: absolute;
  left: 18px;
  top: 28px;
  cursor:
  pointer;
  padding: 10px 35px 16px 0px;
}
#nav-toggle span,
#nav-toggle span:before,
#nav-toggle span:after {
  cursor: pointer;
  border-radius: 1px;
  height: 5px;
  width: 35px;
  background: black;
  position: absolute;
  display: block;
  content: '';
  transition: all 300ms ease-in-out;
}
#nav-toggle span:before {
  top: -10px;
}
#nav-toggle span:after {
  bottom: -10px;
}
#nav-toggle.active span {
  background-color: transparent;
}
#nav-toggle.active span:before, #nav-toggle.active span:after {
  top: 0;
}
#nav-toggle.active span:before {
  transform: rotate(45deg);
}
#nav-toggle.active span:after {
  transform: rotate(-45deg);
}


article {
  max-width: 1000px;
  margin: 0 auto;
  padding: 10px;
}

.container1 {
    background-image: url("{% static 'mysite/images/til.jpg' %}");
    background-size: cover;
    margin: auto;
    padding: 10;
    top: 50;
    background-position: center center;
    text-align: center;
    text-color: white;
    background-repeat: no repeat;
    height: 400px;
    opacity: 0.4;
    overflow: hidden;
    background: black;
}
.about p {
    font-size: 130%;
}
.view {
  height: 100%;
}

@media (max-width: 740px) {
  html,
  body,
  header,
  .view {
    height: 100vh;
  }
}

.top-nav-collapse {
  background-color: #78909c !important;
}

.navbar:not(.top-nav-collapse) {
  background: transparent !important;
}

@media (max-width: 991px) {
  .navbar:not(.top-nav-collapse) {
    background: #78909c !important;
  }
}



h5 {
  letter-spacing: 3px;
  color:white;
  font-size:200%;
}

body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
  }
  h2 {
  font-size: 1em;
  text-transform: capitalize;
}

/* 1. Fallback background-image, if linear-gradient isn't supported. */
.container3 {
  padding: 2em;
  background-image: url('{% static 'mysite/images/til.jpg' %}');
  /* 1 */
  background-image:
    linear-gradient(hsla(300, 80%, 20%, 0.7),90%,coral),
    url('{% static 'mysite/images/til.jpg' %}');
  background-position: center center;
  background-size: cover;
    height:600px;
    background-repeat: no-repeat;
}

.content {
  text-align: center;
  color: white;
}
.hr-light {
  border-top: 3px solid #fff;
  width: 80px;
}
.footer {
   left: 0;
   bottom: 0;
   width: 100%;
   background-color: #F0F8FF;
   color: black;
   text-align: center;
}

ul1 {
    padding: 2px;
    font-size: 35px;
    width: 30px;
    margin: 5px 2px;
    border-radius: 50%;
    list-style: none;
    transition: 6%
    line-height: 60%;
    color: #000;
}

li1 {
    list-style: none;
    margin: 0 10px;
}

.fa {
    color: #000;
    transition: 6%;
    line-height: 60px;
}

h2 {
font-size: 150%;
color: #000;
}

h1 {
font-size: 200%;
color: #000;
.container2 ul li a  {
    position: relative;
    display: block;
    width: 60px;
    padding: 10;
    height: 60px;
    border-radius: 90%;
    background-color:#fff;
    text-align: center;
    transition: 6%;
    box-shadow: 0 5px 4px rgba(0,0,0,.5);
}

 li1:hover{
    transform: translate(0,-10px);










</style>
    <style>
        p {
            font-size: 120%;
    </style>


<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script  src="function.js"></script>
<script>/** code by webdevtrick ( https://webdevtrick.com ) **/
$(document).on('ready', function() {

  $('.field').on('focus', function() {
    $('body').addClass('is-focus');
  });

  $('.field').on('blur', function() {
    $('body').removeClass('is-focus is-type');
  });

  $('.field').on('keydown', function(event) {
    $('body').addClass('is-type');
    if((event.which === 8) && $(this).val() === '') {
      $('body').removeClass('is-type');
    }
  });

});
</script>


<body>

<section class="nav-bar">
    <div class="nav-container">
        <div class="brand mt-2">
            <a href="/" class="logo text-dark">Allshops</a>
        </div>
    </div>
    <nav>
        <div class="nav-mobile"><a id="nav-toggle" href="#!"><span></span></a></div>
        <ul class="nav-list">
            <li>
                <a href="/">Home</a>
            </li>
            <li>
                <a href="/about">About Me</a>
            </li>
            <li>
                <a href="#">My Work</a>
                <ul class="nav-dropdown">
                    <li>
                        <a href="/matlab">MATLAB Projects</a>
                    </li>
                    <li>
                        <a href="/web">Web Development Projects</a>
                    </li>
                    <li>
                        <a href="/proteus">Proteus projects</a>
                    </li>
                </ul>
            </li>
            <li>
                {% if request.user.is_authenticated %}

                <a href="{% url "account:logout" %}">Logout</a>
                {% else %}
                <a href="{% url "account:login" %}">Log-in</a>
                {% endif %}
            </li>
        </ul>
    </nav>
    </div>
</section>
</div>
<script src="http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
<script  src="function.js"></script>
<script>/** code by webdevtrick ( https://webdevtrick.com ) **/
(function($) {
  $(function() {
    $('nav ul li a:not(:only-child)').click(function(e) {
      $(this).siblings('.nav-dropdown').toggle();
      $('.dropdown').not($(this).siblings()).hide();
      e.stopPropagation();
    });
    $('html').click(function() {
      $('.nav-dropdown').hide();
    });
    $('#nav-toggle').click(function() {
      $('nav ul').slideToggle();
    });
    $('#nav-toggle').on('click', function() {
      this.classList.toggle('active');
    });
  });
})(jQuery);
// Animations init
new WOW().init();

</script>
</body>

myshop/shop/templates/shop/pagination.html
<div class="pagination">
    <span class="step-links">
        {% if page.has_previous %}
            <a class="text-success border" href="?page={{ page.previous_page_number }}"><i class="text-success bi bi-chevron-double-left"></i> Previous</a>
        {% endif %}
        <span class="current border text-muted"> Page {{ page.number }} of {{ page.paginator.num_pages }}
        </span>
        {% if page.has_next %}
            <a class="text-success border" href="?page={{ page.next_page_number }}">Next <i class="text-success bi bi-chevron-double-right"></i></a>
        {% endif %}
    </span>
</div>